name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.15.2
        pip install webdriver-manager==4.0.1  
        pip install customtkinter==5.2.0
        pip install Pillow==10.1.0
        pip install pyinstaller==6.2.0
    
    - name: Find CustomTkinter location
      id: find-ctk
      run: |
        $ctkPath = python -c "import customtkinter; import os; print(os.path.dirname(customtkinter.__file__))"
        echo "CTK_PATH=$ctkPath" >> $env:GITHUB_OUTPUT
        echo "Found CustomTkinter at: $ctkPath"
    
    - name: Build EXE (Fixed for CustomTkinter)
      run: |
        pyinstaller --onedir --windowed --name LinkedInChecker --add-data "${{ steps.find-ctk.outputs.CTK_PATH }};customtkinter/" --hidden-import customtkinter --hidden-import PIL --hidden-import selenium --hidden-import webdriver_manager --collect-all customtkinter linkedin_checker.py
    
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: LinkedInChecker-Windows
        path: dist/LinkedInChecker/
